images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
]

wee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify

class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)

    def save(self, *args, **kwargs):
      if not self.slug:
          self.slug = slugify(self.title)
      super().save(*args, **kwargs)

    def __str__(self):
      return self.title
    
    def get_absolute_url(self):
        return reverse("images:detail", args=[self.id, self.slug])
    

images/forms.py
from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify
from urllib import request

from .models import Image

class ImageCreateForm(forms.ModelForm):
  class Meta:
    model = Image
    fields = ('title', 'url', 'description')
    widgets = {
        'url': forms.HiddenInput,
    }

  def clean_url(self):
    url = self.cleaned_data['url']
    valid_extensions = ['jpg', 'jpeg']
    extension = url.rsplit('.', 1)[1].lower()
    if extension not in valid_extensions:
      raise forms.ValidationError('The given URL does not match valid image extensions.')
    return url
  
  def save(self, force_insert=False, force_update=False, commit=True):
    image = super().save(commit=False)
    image_url = self.cleaned_data['url']
    name = slugify(image.title)
    extension = image_url.rsplit('.', 1)[1].lower()
    image_name = f'{name}.{extension}'

    response = request.urlopen(image_url)
    image.image.save(image_name, ContentFile(response.read()), save=False)

    if commit:
      image.save()
    return image

images/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages

from .models import Image
from .forms import ImageCreateForm

@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            messages.success(request, 'Image added successfully')

            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)
      
    return render(request, 'images/image/create.html', {
        'section': 'images',
        'form': form
    })

def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    return render(request, 'images/image/detail.html', {
        'section': 'images',
        'image': image
    })

@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({
                'status': 'ok'
            })
        except:
            pass

        return JsonResponse({'status': 'error'})

images/templates/images/image/create.html
{% extends 'base.html' %}

{% block title %}Bookmark an image{% endblock title %}

{% block content %}
  <h1>Bookmark an image</h1>
  <img src="{{ request.GET.url }}" class="image-preview">
  <form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value= "Bookmark it!">
  </form>
{% endblock content %}

images/templates/images/image/detail.html
{% extends 'base.html' %}

{% block title %}{{ image.title }}{% endblock title %}

{% block content %}
  <h1>{{ image.title }}</h1>
  {% load thumbnail %}
  <a href="{{ image.image.url }}">
    <img src="{% thumbnail image.image 300x0 %}" class="image-detail">
  </a>

  {% with  total_likes=image.users_like.count users_like=image.users_like.all  %}
    <div class="image-info">
      <div>
        <span class="count">
          <span class="total">{{ total_likes }}</span>
          like{{ total_likes|pluralize}}
        </span>
        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
          {% if request.user not in users_like %}
          Like
          {% else %}
          Unlike
          {% endif %}
        </a>
      </div>
      {{ image.description|linebreaks}}
    </div>
    <div class="image-likes">
      {% for user in users_like  %}
        <div>
          <img src="{{ user.profile.photo.url }}">
          <p>{{ user.first_name }}</p>
        </div>
        {% empty %}
        No likes yet
      {% endfor %}
    </div>
  {% endwith %}
{% endblock content %}

{% block domready %}
    $('a.like').click(function(e) {
      e.preventDefault();
      $.post('{% url "images:like" %}', {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data) {
        if (data['status'] == 'ok') {
          let previous_action = $('a.like').data('action');

          $('a.like').data('action', previous_action == 'like' ? 'unlike': 'like');

          $('a.like').test(previous_action == 'like' ? 'Unlike' : 'Like');

          let previous_likes = parseInt($('span.count .total').text());

          $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
        }
      }
      )
    })
{% endblock domready %}